name: Build, Deploy, and Push to AWS ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1 

jobs:
  build_and_push:  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Add Terraform steps to create ECR repository
    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      run: terraform apply -auto-approve

    - name: Get ECR Repository URI
      id: ecr-uri
      run: echo "::set-output name=ecr_repository_uri::$(terraform output ecr_repository_uri)"

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t ${{ steps.ecr-uri.outputs.ecr_repository_uri }}:${{ github.sha }} .
        docker tag ${{ steps.ecr-uri.outputs.ecr_repository_uri }}:${{ github.sha }} ${{ steps.ecr-uri.outputs.ecr_repository_uri }}:latest
        docker push ${{ steps.ecr-uri.outputs.ecr_repository_uri }}:${{ github.sha }}
        docker push ${{ steps.ecr-uri.outputs.ecr_repository_uri }}:latest
